### ISSUE TITLE
multiple dockerfiles, multiple processes

### ISSUE THREAD

**Issue by laterne** [digitalocean-mako/mako#14]
Hi
will it be possible to provide different dockerfiles for web and worker processes? Would this be handled in `mako.yml` like

```
services:
  web:
    command: start-node-web
    http_port: 3000
    build:
      dockerfile: .mako/deploy/DockerfileWeb
  worker:
    command: start-node-worker
    build:
      dockerfile: .mako/deploy/DockerfileWorker
```
