### ISSUE TITLE
cron jobs

### ISSUE THREAD

**Issue by laterne** [digitalocean-mako/mako#15]
Hi
I assume there will be the possibility ti add cron jobs. How will they be specified? Are they entries in `mako.yml` that will point to scripts that get called in the specified interval?

**Comment by jonfriesen** [comment]
Hi @laterne 
This is an area we are still exploring and aren't exactly clear on how we are going to handle this type of action. With that, could you tell me a bit more about how you would use interval or time based script execution?

Thanks! Looking forward to your thoughts :slightly_smiling_face:

**Comment by laterne** [comment]
Hi, thanks, for testing purposes I am trying to port over an app currently running on nanobox. I am using the following tasks:

1. Remove unused files (user uploads and other old files) from object storage. This task is for long term maintenance to prevent the accumulation of unused files. This task is not very time sensitive so it runs only daily
2. Check for data to be pushed as jobs in a queue. This task runs hourly since it checks different time sensitive conditions that decides if a job needs to be pushed.
3. cleanup old unused database entries that are no longer needed. This task runs daily. Also for long term maintenance 

All tasks need Database and object storage access. The second task also accesses the queue (redis based). Therefor all scripts would need access to the same environment variables as the web service.

**Comment by jonfriesen** [comment]
@laterne  this is fantastic feedback, I'm going to pass it along to our product owner and see what we can do! Thanks again :slightly_smiling_face:

**Comment by laterne** [comment]
You are welcome. Below an example how the cron jobs are currently configured in nanobox. From a user perspective this configuration style would also work great in `mako.yml`.
```
# mako.yml
services:
  web:
    command: start-node
    http_port: 3000
    build:
      dockerfile: .mako/deploy/Dockerfile
    cron:
      - id: remove-unused-files
        schedule: '0 17 * * 5'
        command: 'node cron/removeUnusedFiles.js'
      - id: check-jobs-queue
        schedule: '30 * * * *'
        command: 'node cron/checkJobsQueue.js'
      - id: rmove-old-db-entries
        schedule: '45 1 * * 4'
        command: 'node cron/removeOldDbEntries.js'
```
